#!/usr/bin/env python

Import("env")
Import("env_modules")

env_modeling = env_modules.Clone()
env_modeling.Prepend(CPPPATH=["#thirdparty/manifold/include", "#thirdparty/xatlas"])
module_obj = []

env_modeling.add_source_files(module_obj, "*.cpp")
env_modeling.add_source_files(module_obj, "core/*.cpp")
env_modeling.add_source_files(module_obj, "editor/*.cpp")

if env["tests"]:
    env_modeling.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_modeling.add_source_files(module_obj, "tests/*.cpp")

    if env["disable_exceptions"]:
        env_modeling.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env.modules_sources += module_obj
