#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_solers_ai = env_modules.Clone()

module_obj = []

env_solers_ai.add_source_files(module_obj, "*.cpp")
env_solers_ai.add_source_files(module_obj, "core/*.cpp")
env_solers_ai.add_source_files(module_obj, "llm/*.cpp")
env_solers_ai.add_source_files(module_obj, "protocol/*.cpp")

if env.editor_build:
    env_solers_ai.add_source_files(module_obj, "editor/*.cpp")

if env["tests"]:
    env_solers_ai.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_solers_ai.add_source_files(module_obj, "tests/*.cpp")

    if env["disable_exceptions"]:
        env_solers_ai.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env.modules_sources += module_obj
