name: 🔗 GHA
on: [push, pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.

  static-checks:
    if: ${{ !vars.DISABLE_GODOT_CI || github.run_attempt > 1 || github.event_name == 'workflow_dispatch' }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  solers-build-check:
    name: 🧠 Solers strict build
    needs: static-checks
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-bin

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: linux-solers-strict
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        run: >-
          scons platform=linuxbsd target=editor dev_mode=yes module_text_server_fb_enabled=yes
          accesskit=no use_llvm=yes linker=lld cache_path=${{ github.workspace }}/.scons_cache/
          redirect_build_objects=no bin/obj/modules/libmodule_solers_ai.linuxbsd.editor.x86_64.llvm.a

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: linux-solers-strict
        continue-on-error: true

  # Second stage: Run all the builds and some of the tests.

  android-build:
    name: 🤖 Android
    needs: solers-build-check
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: 🍏 iOS
    needs: solers-build-check
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    needs: solers-build-check
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    needs: solers-build-check
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    needs: solers-build-check
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: 🌐 Web
    needs: solers-build-check
    uses: ./.github/workflows/web_builds.yml
